In [1]:
#numpy assigment

In [3]:
""" theorytical question answer's:

1. Purpose and Advantages of NumPy

NumPy is used for performing fast numerical computations in Python. It provides powerful tools for handling large datasets and mathematical operations.
Advantages:

Faster than Python lists
Uses less memory
Supports multi-dimensional arrays
Provides many built-in mathematical functions



2. Difference between np.mean() and np.average()

np.mean() calculates the simple average of elements.
np.average() can calculate both simple and weighted averages.

Use:

Use mean() for normal average
Use average() when weights are given



3. Reversing a NumPy Array

A NumPy array can be reversed in different ways:

For 1D array: arr[::-1]
For 2D array:
np.flipud(arr) → reverses rows (up-down)
np.fliplr(arr) → reverses columns (left-right)



4. Determining Data Type

The data type of elements in a NumPy array can be found using:

arr.dtype

Importance:

Saves memory
Improves performance
Ensures correct calculations



5. ndarray in NumPy

An ndarray is the main object in NumPy. It is a multi-dimensional array that stores elements of the same data type.

Key Features:

Homogeneous data
Fast processing
Supports multiple dimensions

Difference from Python list:

Faster
More memory efficient
Supports advanced operations




6. Performance Benefits of NumPy

NumPy arrays are faster than Python lists because:

They use vectorized operations
No need for loops
Optimized in C language




7. vstack() vs hstack()
vstack() → stacks arrays vertically (one above another)
hstack() → stacks arrays horizontally (side by side)





8. fliplr() vs flipud()
fliplr() → flips array left to right
flipud() → flips array upside down



9. array_split() Function

The array_split() function divides an array into multiple sub-arrays.
It can handle unequal divisions when equal splitting is not possible.




10. Vectorization and Broadcasting

Vectorization allows operations on entire arrays without using loops.
Broadcasting allows operations between arrays of different sizes.

Benefits:

Faster execution
Less code
Efficient computation
"""

" theorytical question answer's:\n\n1. Purpose and Advantages of NumPy\n\nNumPy is used for performing fast numerical computations in Python. It provides powerful tools for handling large datasets and mathematical operations.\nAdvantages:\n\nFaster than Python lists\nUses less memory\nSupports multi-dimensional arrays\nProvides many built-in mathematical functions\n\n\n\n2. Difference between np.mean() and np.average()\n\nnp.mean() calculates the simple average of elements.\nnp.average() can calculate both simple and weighted averages.\n\nUse:\n\nUse mean() for normal average\nUse average() when weights are given\n\n\n\n3. Reversing a NumPy Array\n\nA NumPy array can be reversed in different ways:\n\nFor 1D array: arr[::-1]\nFor 2D array:\nnp.flipud(arr) → reverses rows (up-down)\nnp.fliplr(arr) → reverses columns (left-right)\n\n\n\n4. Determining Data Type\n\nThe data type of elements in a NumPy array can be found using:\n\narr.dtype\n\nImportance:\n\nSaves memory\nImproves performan

In [4]:
#practical question's answer:

#1.
import numpy as np

arr = np.random.randint(1, 100, (3,3))
print(arr)

print(arr.T)   # transpose (rows ↔ columns)

[[47 84 59]
 [95 83 91]
 [64 83 74]]
[[47 95 64]
 [84 83 83]
 [59 91 74]]


In [5]:
#2.
arr = np.arange(10)
print(arr.reshape(2,5))
print(arr.reshape(5,2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [6]:
#3.
arr = np.random.rand(4,4)
new_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(new_arr)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.06484322 0.65798104 0.66086772 0.78675805 0.        ]
 [0.         0.60121415 0.11836102 0.13459182 0.43219331 0.        ]
 [0.         0.92479205 0.72240827 0.11854444 0.12977412 0.        ]
 [0.         0.6499982  0.0365295  0.87977434 0.147294   0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [7]:
#4.
arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


In [8]:
#5.
arr = np.array(['python', 'numpy', 'pandas'])

print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [9]:
#6.
arr = np.array(['hello', 'world'])

result = np.char.join(' ', arr)
print(result)

['h e l l o' 'w o r l d']


In [10]:
#7.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [11]:
#8.
arr = np.eye(5)
print(arr)

print(np.diag(arr))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [12]:
#9.
arr = np.random.randint(0, 1000, 100)

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

primes = [x for x in arr if is_prime(x)]
print(primes)

[np.int64(11), np.int64(163), np.int64(617), np.int64(283), np.int64(797), np.int64(709), np.int64(491), np.int64(677), np.int64(643), np.int64(383), np.int64(653), np.int64(587), np.int64(383), np.int64(479), np.int64(251), np.int64(467), np.int64(191)]


In [13]:
#10.
temps = np.random.randint(20, 40, 30)

weeks = np.array_split(temps, 4)

for i, week in enumerate(weeks):
    print(f"Week {i+1} avg:", np.mean(week))

Week 1 avg: 30.0
Week 2 avg: 30.5
Week 3 avg: 29.857142857142858
Week 4 avg: 25.571428571428573
